### ISSUE TITLE
error message when installing the module

### ISSUE THREAD

**Issue by Romanec31** [muk-it/odoo-modules#29]
Hi,

My odoo 18 is installed in my Pc windows, with the demo database.
I used the integrated import module import, then I got that error message 👍 

Opération invalide
Erreur lors de l'importation du module 'muk_web_appsbar'. while parsing file:/c:/windows/servic~1/locals~1/appdata/local/temp/tmphvd8dk6r/muk_web_appsbar/views/res_users.xml:5 Erreur lors de la validation de la vue : <form string="Users" edit="1"> <widget name="notification_alert"/> <field name="image_1920" readonly="0" widget="image" class="oe_avatar" options="{&quot;preview_image&quot;: &quot;avatar_128&quot;}"/> <h1> Le champ "sidebar_type" n'existe pas dans le modèle "res.users" View error context: {'file': 'c:\\windows\\servic~1\\locals~1\\appdata\\local\\temp\\tmphvd8dk6r\\muk_web_appsbar\\views\\res_users.xml', 'line': 2, 'name': 'res.users.form', 'view': ir.ui.view(3426,), 'view.model': 'res.users', 'view.parent': ir.ui.view(170,), 'xmlid': 'view_res_users_form'}

**Comment by Romanec31** [comment]
![Image](https://github.com/user-attachments/assets/20f0b05b-76e8-4ea4-8f74-0ac88d604e02)

**Comment by keshrath** [comment]
Please install the module as described in the documentation

![Image](https://github.com/user-attachments/assets/716c3888-0ffc-4219-9413-abc436429246)

**Comment by Romanec31** [comment]
Hi,

OK the issue is solved.

You should explain to beginners that they will not see you your app unless they remove the "APP" in the search ..
I will update my rating on the website, as it working,

Thanks,

Romain


![Image](https://github.com/user-attachments/assets/df90681d-541b-42bd-b974-cf4b9bcaa366)

**Comment by vidsava** [comment]
I got same problem and I try to search with take off "APP" still not found muk too.

![Image](https://github.com/user-attachments/assets/b246b58d-2460-427e-8231-3e1194fd235a)
![Image](https://github.com/user-attachments/assets/fd7b2651-d9be-4ca7-b310-968f731b2682)
![Image](https://github.com/user-attachments/assets/320519dd-fa80-43fc-bef4-8dac3711be51)

**Comment by vidsava** [comment]
Can Any one help???

**Comment by dodyindrajaya** [comment]
please check last post, it same issue
works on me
